In [ ]:
 print("hi")

hi

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data =[1,2,3,4,5]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
s2 = pd.Series({'X':100,'Y':200,'Z':300})
print(s2)

X    100
Y    200
Z    300
dtype: int64

In [ ]:
#accessing
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[:6])

0    g
1    e
2    e
3    k
4    s
5    f
dtype: object

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[-3:])

10    e
11    k
12    s
dtype: object

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[:-2])

0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    e
dtype: object

In [ ]:
#updating
s1 = pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s1)
#updating
s1['a'] = 99
print(s1)

a    10
b    20
c    30
d    40
dtype: int64
a    99
b    20
c    30
d    40
dtype: int64

In [ ]:
#adding the element
s1['e'] = 50
print(s1)

a    99
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
#delete the element
s1 = s1.drop('b')
print(s1)

a    99
c    30
d    40
e    50
dtype: int64

In [ ]:
students_Series = pd.Series(data=[78,85,92,67,88],index=[100,102,103,104,105])

In [ ]:
students_Series[103]

np.int64(92)

In [ ]:
import pandas as pd
EmployeeID = [1001,1002,1003,1004,1005]
salary = [3500,42000,38000,50000,45000]
ser = pd.Series(salary,index=EmployeeID)
print(ser)

1001     3500
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64

In [ ]:
EmployeeID = [1001,1002,1003,1004,1005]
salary = [3500,42000,38000,50000,45000]
ser = pd.Series(salary,index=EmployeeID)
print(ser[1003],)

38000

In [ ]:
student_ids = [101,102,103,104,105]
marks = [78,85,92,67,88]

In [ ]:
student_series = pd.Series(marks, index=student_ids, name="Marks")
print("Initial Series:")
print(student_series)
print("-" * 20)

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd
student_series = pd.Series(marks, index=student_ids, name="Marks")
print("Initial Series:")
print(student_series)
print("-" * 20)

Initial Series:
101    78
102    85
103    92
104    67
105    88
Name: Marks, dtype: int64
--------------------

In [ ]:
import pandas as pd
marks_103 = student_series[103]
print(f"Marks of student 103: {marks_103}")
print("-" * 20)

Marks of student 103: 92
--------------------

In [ ]:
import pandas as pd
student_series[104] = 75
print("Series after changing student 104's marks to 75:")
print(student_series)
print("-" * 20)

Series after changing student 104's marks to 75:
101    78
102    85
103    92
104    75
105    88
Name: Marks, dtype: int64
--------------------

In [ ]:
import pandas ass pd
student_series = student_series.drop(102)
print("Series after deleting student 102:")
print(student_series)
print("-" * 20)

SyntaxError: invalid syntax (2985776315.py, line 1)

In [ ]:
import pandas as pd
student_series = student_series.drop(102)
print("Series after deleting student 102:")
print(student_series)
print("-" * 20)

Series after deleting student 102:
101    78
103    92
104    75
105    88
Name: Marks, dtype: int64
--------------------

In [ ]:
import pandas as pd
student_series[106] = 98
print("Final Series after adding student 106:")
print(student_series)

Final Series after adding student 106:
101    78
103    92
104    75
105    88
106    98
Name: Marks, dtype: int64

In [ ]:
import pandas as pd
emp_ids = [1001, 1002, 1003, 1004, 1005]
salaries = [35000, 42000, 38000, 50000, 45]

In [ ]:
import pandas as pd
employee_series = pd.Series(salaries, index=emp_ids, name="Salary")
print("Initial Series:")
print(employee_series)
print("-" * 20)

Initial Series:
1001    35000
1002    42000
1003    38000
1004    50000
1005       45
Name: Salary, dtype: int64
--------------------

In [ ]:
import pandas as pd
employee_series[1003] = 40000
print("Series after increasing employee 1003's salary:")
print(employee_series)
print("-" * 20)

Series after increasing employee 1003's salary:
1001    35000
1002    42000
1003    40000
1004    50000
1005       45
Name: Salary, dtype: int64
--------------------

In [ ]:
import pandas as pd
employee_series = employee_series.drop(1002)
print("Series after deleting employee 1002:")
print(employee_series)
print("-" * 20)

Series after deleting employee 1002:
1001    35000
1003    40000
1004    50000
1005       45
Name: Salary, dtype: int64
--------------------

In [ ]:
import pandas as pd
employee_series[1006] = 55000
print("Series after adding employee 1006:")
print(employee_series)
print("-" * 20)

Series after adding employee 1006:
1001    35000
1003    40000
1004    50000
1005       45
1006    55000
Name: Salary, dtype: int64
--------------------

In [ ]:
import pandas as pd
print("First 3 employees:")
print(employee_series.head(3))

First 3 employees:
1001    35000
1003    40000
1004    50000
Name: Salary, dtype: int64

In [ ]:
import pandas as pd
prod_ids = ['P101', 'P102', 'P103', 'P104', 'P105']
prices = [500, 750, 1200, 900, 1500]

In [ ]:
import pandas as pd
product_series = pd.Series(prices, index=prod_ids, name="Price")
print("Initial Series:")
print(product_series)
print("-" * 20)

Initial Series:
P101     500
P102     750
P103    1200
P104     900
P105    1500
Name: Price, dtype: int64
--------------------

In [ ]:
import pandas as pd
price_p103 = product_series['P103']
print(f"Price of P103: {price_p103}")
print("-" * 20)

Price of P103: 1200
--------------------

In [ ]:
import pandas as pd
product_series['P102'] = 800
print("Series after changing P102's price:")
print(product_series)
print("-" * 20)

Series after changing P102's price:
P101     500
P102     800
P103    1200
P104     900
P105    1500
Name: Price, dtype: int64
--------------------

In [ ]:
import pandas as pd
product_series = product_series.drop('P104')
print("Series after deleting P104:")
print(product_series)
print("-" * 20)

Series after deleting P104:
P101     500
P102     800
P103    1200
P105    1500
Name: Price, dtype: int64
--------------------

In [ ]:
import pandas as pd
product_series['P106'] = 2000
print("Final Series after adding P106:")
print(product_series)

Final Series after adding P106:
P101     500
P102     800
P103    1200
P105    1500
P106    2000
Name: Price, dtype: int64

In [ ]:
import pandas as pd
temperatures = [31, 32, 34, 33, 35, 36, 34]
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weather_series = pd.Series(temperatures, index=days, name='Temperature')

print("1. Original Series:")
print(weather_series)
print("-" * 20)

1. Original Series:
Monday       31
Tuesday      32
Wednesday    34
Thursday     33
Friday       35
Saturday     36
Sunday       34
Name: Temperature, dtype: int64
--------------------

In [ ]:
import pandas as pd
print("2. Temperature from Monday to Wednesday:")
print(mon_to_wed)
print("-" * 20)

2. Temperature from Monday to Wednesday:

NameError: name 'mon_to_wed' is not defined

In [ ]:
import pandas as pd
temperatures = [31, 32, 34, 33, 35, 36, 34]
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weather_series = pd.Series(temperatures, index=days, name='Temperature')

In [ ]:
import pandas as pd
print("1. Original Series:")
print(weather_series)
print("-" * 20)

1. Original Series:
Monday       31
Tuesday      32
Wednesday    34
Thursday     33
Friday       35
Saturday     36
Sunday       34
Name: Temperature, dtype: int64
--------------------

In [ ]:
import pandas as pd
mon_to_wed = weather_series['Monday':'Wednesday']

In [ ]:
import pandas as pd
print("2. Temperature from Monday to Wednesday:")
print(mon_to_wed)
print("-" * 20)

2. Temperature from Monday to Wednesday:
Monday       31
Tuesday      32
Wednesday    34
Name: Temperature, dtype: int64
--------------------

In [ ]:
import pandas as pd
weather_series['Thursday'] = 32

In [ ]:
import pandas as pd
print("3. Series after changing Thursday's temperature:")
print(weather_series)
print("-" * 20)

3. Series after changing Thursday's temperature:
Monday       31
Tuesday      32
Wednesday    34
Thursday     32
Friday       35
Saturday     36
Sunday       34
Name: Temperature, dtype: int64
--------------------

In [ ]:
import pandas as pd
weather_series = weather_series.drop('Saturday')

In [ ]:
import pandas as pd
print("4. Series after deleting Saturday:")
print(weather_series)
print("-" * 20)

4. Series after deleting Saturday:
Monday       31
Tuesday      32
Wednesday    34
Thursday     32
Friday       35
Sunday       34
Name: Temperature, dtype: int64
--------------------

In [ ]:
import pandas as pd
weather_series['Monday_Next'] = 38

In [ ]:
import pandas as pd
print(weather_series)

Monday         31
Tuesday        32
Wednesday      34
Thursday       32
Friday         35
Sunday         34
Monday_Next    38
Name: Temperature, dtype: int64

In [ ]:
import pandas as pd
account_ids = ['A101', 'A102', 'A103', 'A104', 'A105']
balances = [25000, 45000, 32000, 18000, 60000]

In [ ]:
import pandas as pd
bank_balances = pd.Series(balances, index=account_ids)
print("1. Initial Series:")
print(bank_balances)
print("-" * 20)

1. Initial Series:
A101    25000
A102    45000
A103    32000
A104    18000
A105    60000
dtype: int64
--------------------

In [ ]:
import pandas as pd
balance_a103 = bank_balances['A103']
print(f"2. Balance of A103: {balance_a103}")
print("-" * 20)

2. Balance of A103: 32000
--------------------

In [ ]:
import pandas as pd
bank_balances['A104'] = 25000
print("3. Series after updating A104:")
print(bank_balances)
print("-" * 20)

3. Series after updating A104:
A101    25000
A102    45000
A103    32000
A104    25000
A105    60000
dtype: int64
--------------------

In [ ]:
import pandas as pd
bank_balances = bank_balances.drop('A101')
print("4. Series after deleting A101:")
print(bank_balances)
print("-" * 20)

4. Series after deleting A101:
A102    45000
A103    32000
A104    25000
A105    60000
dtype: int64
--------------------

In [ ]:
import pandas as pd
bank_balances['A106'] = 40000
print("5. Final Series after adding A106:")
print(bank_balances)

5. Final Series after adding A106:
A102    45000
A103    32000
A104    25000
A105    60000
A106    40000
dtype: int64

In [ ]:
#dataframes creation
#usingb list
import pandas as pd
data = [
    ["Ravi",22,30000],
    ["priya",24,40000],
    ["Arun",21,28000]
]
df = pd.DataFrame(data,columns=["Name","Age","Salary"])
print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  priya   24   40000
2   Arun   21   28000

In [ ]:
by using tuple:
data = (
    ("Ravi",22,30000),
    ("Priya",24,40000),
    ("Arun",21,28000)
)
data = pd.DataFrame(data,columns=("Name","Age","Salary"))
print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  priya   24   40000
2   Arun   21   28000

In [ ]:
#Dictionary
data ={
    'Name': ['Alice','Bob','Charlie'],
    'Age': [25,30,35],
    'City': ['NY','LA','Chicago']}
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

In [ ]:
#create a dataframe sales and profit of every month in the first 6 monthsof the year
import pandas as pd
sales_data ={
    'Month':['Jan','Feb','Mar','Apr','May','Jun'],
    'Sales': ['mouse','booke','pen','keyboard','laptop','tv']}
df = pd.DataFrame(sales_data)
print(df)

IndentationError: unexpected indent (2571862418.py, line 7)

In [ ]:
#set
my_set ={100,200,300,400}
df= pd.DataFrame(list(my_set),columns=['Values'])
print(df)

   Values
0     200
1     100
2     400
3     300

In [ ]:
s = pd.Series(
    [1,2,3,4],
    name='Numbers')
df =s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [ ]:
s2 =pd.Series([9,6,5,8])
s3 =pd.Series([12,13,14,15])
d={
    "marks-A" :s,
    "marks-B" :s2,
    "marks-C" :s3}
df = pd.DataFrame(d)
print(df)

   marks-A  marks-B  marks-C
0        1        9       12
1        2        6       13
2        3        5       14
3        4        8       15

In [ ]:
s = pd.Series(
    [1,2,3,4],
    name='Numbers')
df =s.to_frame()
df.columns=["digits"]  #rename
print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
s2 =pd.Series([9,6,5,8])
s3 =pd.Series([12,13,14,15])
d={
    "marks-A" :s,
    "marks-B" :s2,
    "marks-C" :s3}
df = pd.DataFrame(d)
df. columns=["maths","english","physics"]
print(df)

   maths  english  physics
0      1        9       12
1      2        6       13
2      3        5       14
3      4        8       15

In [ ]:
df = pd.DataFrame([
    [1,2],
    [3,4]])
df.columns= ['A','B']
print(df)

   A  B
0  1  2
1  3  4

In [ ]:
#rename
df.rename(columns={'A':'Alpha','B':'Beta'},inplace=True)
print(df)

   Alpha  Beta
0      1     2
1      3     4

In [ ]:
#viewing data
s2 =pd.Series([9,6,5,8,9,4,6,7])
s3 =pd.Series([12,13,14,15,16,17,18,19])
d={
    #"marks-A" :s,
    "marks-B" :s2,
    "marks-C" :s3}
df = pd.DataFrame(d)
df. columns=["da","sql"]  #rename
print(df)
#viewing
print(df.head(7)) #top
print(df.tail()) #bottom
print(len(df))
print(df.shape)
df.index
df.values

   da  sql
0   9   12
1   6   13
2   5   14
3   8   15
4   9   16
5   4   17
6   6   18
7   7   19
   da  sql
0   9   12
1   6   13
2   5   14
3   8   15
4   9   16
5   4   17
6   6   18
   da  sql
3   8   15
4   9   16
5   4   17
6   6   18
7   7   19
8
(8, 2)

array([[ 9, 12],
       [ 6, 13],
       [ 5, 14],
       [ 8, 15],
       [ 9, 16],
       [ 4, 17],
       [ 6, 18],
       [ 7, 19]])

In [ ]:
import pandas as pd
data_list = [
    ['Alice', 28, 'New York', 65000],
    ['Bob', 32, 'London', 72000],
    ['Charlie', 25, 'Paris', 58000],
    ['Diana', 30, 'Tokyo', 81000],
    ['Ethan', 40, 'Berlin', 95000]
]

In [ ]:
df_list = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
print("DataFrame from List of Lists:")
display(df_list)

DataFrame from List of Lists:

      Name  Age      City  Salary
0    Alice   28  New York   65000
1      Bob   32    London   72000
2  Charlie   25     Paris   58000
3    Diana   30     Tokyo   81000
4    Ethan   40    Berlin   95000

In [ ]:
import pandas as pd
data_dict = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam'],
    'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories', 'Electronics'],
    'Price': [1200, 25, 300, 75, 50],
    'Quantity': [10, 50, 15, 30, 20]
}

In [ ]:
df_dict = pd.DataFrame(data_dict)
print("DataFrame from Dictionary:")
display(df_dict)

DataFrame from Dictionary:

    Product     Category  Price  Quantity
0    Laptop  Electronics   1200        10
1     Mouse  Accessories     25        50
2   Monitor  Electronics    300        15
3  Keyboard  Accessories     75        30
4    Webcam  Electronics     50        20

In [ ]:
data_list_dict = [
    {'Student_ID': 'S101', 'Name': 'John', 'Course': 'Math', 'Marks': 88},
    {'Student_ID': 'S102', 'Name': 'Emma', 'Course': 'Science', 'Marks': 92},
    {'Student_ID': 'S103', 'Name': 'Michael', 'Course': 'History', 'Marks': 79},
    {'Student_ID': 'S104', 'Name': 'Sophia', 'Course': 'Math', 'Marks': 95},
    {'Student_ID': 'S105', 'Name': 'William', 'Course': 'Science', 'Marks': 84}
]

In [ ]:
df_list_dict = pd.DataFrame(data_list_dict)
print("DataFrame from List of Dictionaries:")
display(df_list_dict)

DataFrame from List of Dictionaries:

  Student_ID     Name   Course  Marks
0       S101     John     Math     88
1       S102     Emma  Science     92
2       S103  Michael  History     79
3       S104   Sophia     Math     95
4       S105  William  Science     84

In [ ]:
series_name = pd.Series(['Oliver', 'Mia', 'Lucas', 'Ava', 'Leo'])
series_age = pd.Series([22, 27, 24, 31, 29])
series_city = pd.Series(['Chicago', 'Miami', 'Seattle', 'Boston', 'Denver'])

In [ ]:
df_series = pd.DataFrame({
    'Name': series_name,
    'Age': series_age,
    'City': series_city
})

print("DataFrame from Pandas Series:")
display(df_series)

In [ ]:

import pandas as pd
data ={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "city":["Hyderbad","Chennai","Banglore","Hyderbad",
            "Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,32000,35000,45000,25000,55000]}

df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       Name  Age      city  Salary
101    Ravi   22  Hyderbad   30000
102   Priya   24   Chennai   40000
103    Arun   21  Banglore   28000
104   Sneha   25  Hyderbad   32000
105   Kiran   23    Mumbai   35000
106  Anjali   26   Chennai   45000
107  Vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000

In [ ]:
#viewing and selecting data
print(df.head())
print("...............................")
print(df.tail())
print("...............................")
print(df.info())
print("...............................")
print(df.describe())
print("...............................")
print(len(df))
print("...............................")
print(df.shape)
print("...............................")
print(df.index)
print("...............................")
print(df)

    Name  Age      city  Salary
0   Ravi   22  Hyderbad   30000
1  Priya   24   Chennai   40000
2   Arun   21  Banglore   28000
3  Sneha   25  Hyderbad   32000
4  Kiran   23    Mumbai   35000
...............................
     Name  Age      city  Salary
3   Sneha   25  Hyderbad   32000
4   Kiran   23    Mumbai   35000
5  Anjali   26   Chennai   45000
6  Vikram   20  Banglore   25000
7   Meena   27    Mumbai   55000
...............................
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   city    8 non-null      object
 3   Salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes
None
...............................
            Age        Salary
count   8.00000      8.000000
mean   23.50000  36250.000000
std     2.44949   9967.805318
min    20.00000  25000.000000
25%    21.75000  29500.000000
50%    23.50000  33500.000000
75%    25.25000  41250.000000
max    27.00000  55000.000000
...............................
8
...............................
(8, 4)
...............................
RangeIndex(start=0, stop=8, step=1)
...............................
     Name  Age      city  Salary
0    Ravi   22  Hyderbad   30000
1   Priya   24   Chennai   40000
2    Arun   21  Banglore   28000
3   Sneha   25  Hyderbad   32000
4   Kiran   23    Mumbai   35000
5  Anjali   26   Chennai   45000
6  Vikram   20  Banglore   25000
7   Meena   27    Mumbai   55000

In [ ]:
print(df[["Name",'Age']])

     Name  Age
0    Ravi   22
1   Priya   24
2    Arun   21
3   Sneha   25
4   Kiran   23
5  Anjali   26
6  Vikram   20
7   Meena   27

In [ ]:
df.iloc[0:3]

      Name  Age      city  Salary
101   Ravi   22  Hyderbad   30000
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000

In [ ]:
df.loc[103:105]

      Name  Age      city  Salary
103   Arun   21  Banglore   28000
104  Sneha   25  Hyderbad   32000
105  Kiran   23    Mumbai   35000

In [ ]:
df["Salary"]>45000

101    False
102    False
103    False
104    False
105    False
106    False
107    False
108     True
Name: Salary, dtype: bool

In [ ]:
df["Salary"]<35000

101     True
102    False
103     True
104     True
105    False
106    False
107     True
108    False
Name: Salary, dtype: bool

In [ ]:
df[df["Salary"]<35000]

       Name  Age      city  Salary
101    Ravi   22  Hyderbad   30000
103    Arun   21  Banglore   28000
104   Sneha   25  Hyderbad   32000
107  Vikram   20  Banglore   25000

In [ ]:
 import pandas as pd
 data ={
     "Student_ID":[101,102,103,104,105,106,107,108,109,110],
     "Name": ["Aarav","Priya","Rahul","Sneha","Arjun",
              "Divya","Kiran","Ananya","ROHIT","Meena"],
     "Age": [20,21,19,22,20,21,23,19,22,20],
     "Course": ["Python","PoweR BI","python","Excel","Python",
                "Power BI","Excel","Python","Power BI","Excel"],
     "Marks": [85,78,92,67,88,74,81,95,69,90],
     "Attendance": [92,85,96,78,89,82,91,98,75,94],
     "City": ["Hyderbad","Chennai","Bangloar","Hyderbad","pune",
              "Chennai","Bangloar","Hyderbad","pune","Hyderbad"]}
df = pd.DataFrame(data)
print(df)

   Student_ID    Name  Age    Course  Marks  Attendance      City
0         101   Aarav   20    Python     85          92  Hyderbad
1         102   Priya   21  PoweR BI     78          85   Chennai
2         103   Rahul   19    python     92          96  Bangloar
3         104   Sneha   22     Excel     67          78  Hyderbad
4         105   Arjun   20    Python     88          89      pune
5         106   Divya   21  Power BI     74          82   Chennai
6         107   Kiran   23     Excel     81          91  Bangloar
7         108  Ananya   19    Python     95          98  Hyderbad
8         109   ROHIT   22  Power BI     69          75      pune
9         110   Meena   20     Excel     90          94  Hyderbad

In [ ]:
df = pd.DataFrame(data)
print(df)

   Student_ID    Name  Age    Course  Marks  Attendance      City
0         101   Aarav   20    Python     85          92  Hyderbad
1         102   Priya   21  PoweR BI     78          85   Chennai
2         103   Rahul   19    python     92          96  Bangloar
3         104   Sneha   22     Excel     67          78  Hyderbad
4         105   Arjun   20    Python     88          89      pune
5         106   Divya   21  Power BI     74          82   Chennai
6         107   Kiran   23     Excel     81          91  Bangloar
7         108  Ananya   19    Python     95          98  Hyderbad
8         109   ROHIT   22  Power BI     69          75      pune
9         110   Meena   20     Excel     90          94  Hyderbad

In [ ]:
df.head(5)

   Student_ID   Name  Age    Course  Marks  Attendance      City
0         101  Aarav   20    Python     85          92  Hyderbad
1         102  Priya   21  PoweR BI     78          85   Chennai
2         103  Rahul   19    python     92          96  Bangloar
3         104  Sneha   22     Excel     67          78  Hyderbad
4         105  Arjun   20    Python     88          89      pune

In [ ]:
df.tail(3)

   Student_ID    Name  Age    Course  Marks  Attendance      City
7         108  Ananya   19    Python     95          98  Hyderbad
8         109   ROHIT   22  Power BI     69          75      pune
9         110   Meena   20     Excel     90          94  Hyderbad

In [ ]:
df[["Student_ID","Course","Marks"]].iloc[0:4]

   Student_ID    Course  Marks
0         101    Python     85
1         102  PoweR BI     78
2         103    python     92
3         104     Excel     67

In [ ]:
df[["Marks","Attendance","City"]].iloc[-3:]

   Marks  Attendance      City
7     95          98  Hyderbad
8     69          75      pune
9     90          94  Hyderbad

In [ ]:
#Manipulating data
import pandas as pd
sales = pd.Series(
    [5000,7000,None,9000,8000,10000,None],
    index=["Monday","Tuesday","Wednesday",
           "Thursday","Friday","Saturday","Sunday"])
print(sales)
#aggregations
sales["Tuesday"]=9500
print(sales)
sales["jan"]=7800
print(sales)
sales=sales.drop("Tuesday")

print(sales.min())
print(sales.max())
print(sales.mean())
print(sales.sum())
print(sales.var())
print(sales.std())
print(sales.dtype) #check the data type

#updating & insertion of new

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64
Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64
Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64
5000.0
10000.0
7960.0
39800.0
3508000.0
1872.9655629509048
float64

In [ ]:
print(sales)

Monday        5000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [ ]:
print(sales+2000)
print(sales*2)

Monday        7000.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
jan           9800.0
dtype: float64
Monday       10000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
jan          15600.0
dtype: float64

In [ ]:
#combine two series
s=pd.Series([1,2,3,4,5])  #index=[9,7,6,8,0])
s1=pd.Series([101,102,103,104,105])#index[901,902,903,904,905])
print(s)
print(s1)
d=pd.concat([s,s1])#incorrect
c=pd.concat([s,s1],ignore_index=True) #correct
print(d)
print(c)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64

In [ ]:
import pandas as pd
data ={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "city":["Hyderbad","Chennai","Banglore","Hyderbad",
            "Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]}

df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df.head())

      Name  Age      city  Salary
101   Ravi   22  Hyderbad   30000
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000
104  Sneha   25  Hyderbad   50000
105  Kiran   23    Mumbai   35000

In [ ]:

print(df["Age"].sum())

188

In [ ]:
print(df["Age"].mean())

23.5

In [ ]:
print(df["Age"].std())

2.449489742783178

In [ ]:
print(df["Age"].count())

8

In [ ]:
print(df["Age"].min())

20

In [ ]:
print(df["Age"].max())

27

In [ ]:
print(df["Age"].median())

23.5

In [ ]:
print(df["Salary"].sum())

308000

In [ ]:
print(df["Salary"].mean())

38500.0

In [ ]:
print(df["Salary"].std())

10862.780491200216

In [ ]:
print(df["Salary"].count())

8

In [ ]:
print(df["Salary"].min())

25000

In [ ]:
print(df["Salary"].max())

55000

In [ ]:
print(df["Salary"].median())

37500.0

In [ ]:
df['Bonus'] =df['Salary'] *0.10
print(df)

       Name  Age      city  Salary   Bonus
101    Ravi   22  Hyderbad   30000  3000.0
102   Priya   24   Chennai   40000  4000.0
103    Arun   21  Banglore   28000  2800.0
104   Sneha   25  Hyderbad   50000  5000.0
105   Kiran   23    Mumbai   35000  3500.0
106  Anjali   26   Chennai   45000  4500.0
107  Vikram   20  Banglore   25000  2500.0
108   Meena   27    Mumbai   55000  5500.0

In [ ]:
df['New Salary']=df['Salary']+df['Bonus']
print(df)

       Name  Age      city  Salary   Bonus  New Salary
101    Ravi   22  Hyderbad   30000  3000.0     33000.0
102   Priya   24   Chennai   40000  4000.0     44000.0
103    Arun   21  Banglore   28000  2800.0     30800.0
104   Sneha   25  Hyderbad   50000  5000.0     55000.0
105   Kiran   23    Mumbai   35000  3500.0     38500.0
106  Anjali   26   Chennai   45000  4500.0     49500.0
107  Vikram   20  Banglore   25000  2500.0     27500.0
108   Meena   27    Mumbai   55000  5500.0     60500.0

In [ ]:
df['Age']=df["Age"]+1
print(df)

       Name  Age      city  Salary   Bonus  New Salary
101    Ravi   24  Hyderbad   30000  3000.0     33000.0
102   Priya   26   Chennai   40000  4000.0     44000.0
103    Arun   23  Banglore   28000  2800.0     30800.0
104   Sneha   27  Hyderbad   50000  5000.0     55000.0
105   Kiran   25    Mumbai   35000  3500.0     38500.0
106  Anjali   28   Chennai   45000  4500.0     49500.0
107  Vikram   22  Banglore   25000  2500.0     27500.0
108   Meena   29    Mumbai   55000  5500.0     60500.0

In [ ]:
df['New Salary']+df['New Salary']+500
print(df)

       Name  Age      city  Salary   Bonus  New Salary
101    Ravi   24  Hyderbad   30000  3000.0     33000.0
102   Priya   26   Chennai   40000  4000.0     44000.0
103    Arun   23  Banglore   28000  2800.0     30800.0
104   Sneha   27  Hyderbad   50000  5000.0     55000.0
105   Kiran   25    Mumbai   35000  3500.0     38500.0
106  Anjali   28   Chennai   45000  4500.0     49500.0
107  Vikram   22  Banglore   25000  2500.0     27500.0
108   Meena   29    Mumbai   55000  5500.0     60500.0

In [ ]:
#updating
df.loc[df['Name']=='Priya','City'] ='Pune'
print(df)

       Name  Age      city  Salary   Bonus  New Salary  City
101    Ravi   24  Hyderbad   30000  3000.0     33000.0   NaN
102   Priya   26   Chennai   40000  4000.0     44000.0  Pune
103    Arun   23  Banglore   28000  2800.0     30800.0   NaN
104   Sneha   27  Hyderbad   50000  5000.0     55000.0   NaN
105   Kiran   25    Mumbai   35000  3500.0     38500.0   NaN
106  Anjali   28   Chennai   45000  4500.0     49500.0   NaN
107  Vikram   22  Banglore   25000  2500.0     27500.0   NaN
108   Meena   29    Mumbai   55000  5500.0     60500.0   NaN

In [ ]:
df.loc[df['City'] =='Banglore','City'] = 'Hyderbad'
print(df)

       Name  Age      city  Salary   Bonus  New Salary  City
101    Ravi   24  Hyderbad   30000  3000.0     33000.0   NaN
102   Priya   26   Chennai   40000  4000.0     44000.0  Pune
103    Arun   23  Banglore   28000  2800.0     30800.0   NaN
104   Sneha   27  Hyderbad   50000  5000.0     55000.0   NaN
105   Kiran   25    Mumbai   35000  3500.0     38500.0   NaN
106  Anjali   28   Chennai   45000  4500.0     49500.0   NaN
107  Vikram   22  Banglore   25000  2500.0     27500.0   NaN
108   Meena   29    Mumbai   55000  5500.0     60500.0   NaN

In [ ]:
df.loc[df['City'] == 'Mum','Salary'] =df["Salary"]*1.05
print(df)

       Name  Age      city  Salary   Bonus  New Salary  City
101    Ravi   24  Hyderbad   30000  3000.0     33000.0   NaN
102   Priya   26   Chennai   40000  4000.0     44000.0  Pune
103    Arun   23  Banglore   28000  2800.0     30800.0   NaN
104   Sneha   27  Hyderbad   50000  5000.0     55000.0   NaN
105   Kiran   25    Mumbai   35000  3500.0     38500.0   NaN
106  Anjali   28   Chennai   45000  4500.0     49500.0   NaN
107  Vikram   22  Banglore   25000  2500.0     27500.0   NaN
108   Meena   29    Mumbai   55000  5500.0     60500.0   NaN

In [ ]:
df.loc[df['Salary'] <45000,'Salary'] =60000
print(df)

       Name  Age      city  Salary   Bonus  New Salary  City
101    Ravi   24  Hyderbad   60000  3000.0     33000.0   NaN
102   Priya   26   Chennai   60000  4000.0     44000.0  Pune
103    Arun   23  Banglore   60000  2800.0     30800.0   NaN
104   Sneha   27  Hyderbad   50000  5000.0     55000.0   NaN
105   Kiran   25    Mumbai   60000  3500.0     38500.0   NaN
106  Anjali   28   Chennai   45000  4500.0     49500.0   NaN
107  Vikram   22  Banglore   60000  2500.0     27500.0   NaN
108   Meena   29    Mumbai   55000  5500.0     60500.0   NaN

In [ ]:
df.drop(
    columns=['Salary'],
    inplace=True)
print(df)

       Name  Age      city  New Salary  City
101    Ravi   24  Hyderbad     33000.0   NaN
102   Priya   26   Chennai     44000.0  Pune
103    Arun   23  Banglore     30800.0   NaN
104   Sneha   27  Hyderbad     55000.0   NaN
105   Kiran   25    Mumbai     38500.0   NaN
106  Anjali   28   Chennai     49500.0   NaN
107  Vikram   22  Banglore     27500.0   NaN
108   Meena   29    Mumbai     60500.0   NaN

In [ ]:
#oct9
reading a file
df = pd.read_csv("sales.csv")

In [ ]:
import pandas as pd
df = pd.DataFrame(
    [5000,7000,None,9000,8000,10000,None],
    index=["Monday","Tuesday","Wednesday","Thursaday","Friday","Saturday","Sunday"])
#print(df)
#cleaning
#handling missing values
#df.isna()
#df.isna().sum()
#df.dropna()

In [ ]:
df.isnull()
df.isnull().sum()
df.fillna("no data")

                 0
Monday      5000.0
Tuesday     7000.0
Wednesday  no data
Thursaday   9000.0
Friday      8000.0
Saturday   10000.0
Sunday     no data

In [ ]:
employees = {
  "EmpID": [101,102,103,104],
  "Name": ["Asha",None,"Meena","sai"],
  "Department": ["Sales","IT","HR",None],
  "Salary": [45000,60000,None,89000]
}
I =[901,902,903,904]
df= pd.DataFrame(employees,index=I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df.fillna({
    'Name' : 'unknown',
    'Salary' : 0,
    'Department' :0
})

     EmpID     Name Department   Salary
901    101     Asha      Sales  45000.0
902    102  unknown         IT  60000.0
903    103    Meena         HR      0.0
904    104      sai          0  89000.0

In [ ]:
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df['Salary'].fillna(df['Salary'].max())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(df['Salary'].min())

901    45000.0
902    60000.0
903    45000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(df['Salary'].std())

901    45000.000000
902    60000.000000
903    22368.132093
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(df['Salary'].mean())

901    45000.000000
902    60000.000000
903    64666.666667
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(df['Salary'].sum())

901     45000.0
902     60000.0
903    194000.0
904     89000.0
Name: Salary, dtype: float64

In [ ]:
import pandas as pd

employees = {
    "EmpID": [101, 102, 103, 104],
    "Name": ["Asha", None, "Meena", "sai"],
    "Department": ["Sales", "IT", "HR", None],
    "Salary": [45000, 60000, None, 89000]
}

I = [901, 902, 903, 904]

df = pd.DataFrame(employees, index=I)

# Display employees whose Name or Department is missing
print(df[df[["Name", "Department"]].isnull().any(axis=1)])

     EmpID  Name Department   Salary
902    102  None         IT  60000.0
904    104   sai       None  89000.0

In [ ]:
df.head(2)

     EmpID  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT  60000.0

In [ ]:
df.tail(2)

     EmpID   Name Department   Salary
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df[['Name','Salary']]

      Name   Salary
901   Asha  45000.0
902   None  60000.0
903  Meena      NaN
904    sai  89000.0

In [ ]:
print(df[df["EmpID"] == 103])

     EmpID   Name Department  Salary
903    103  Meena         HR     NaN

In [ ]:
df['Salary']>50000

901    False
902     True
903    False
904     True
Name: Salary, dtype: bool

In [ ]:
print(df['Department'] =='IT')

901    False
902     True
903    False
904    False
Name: Department, dtype: bool

In [ ]:
print(df[df[["Name", "Department"]].isnull().any(axis=1)])

     EmpID  Name Department   Salary
902    102  None         IT  60000.0
904    104   sai       None  89000.0

In [ ]:
print(df.isnull().sum())

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df["Name"] = df["Name"].fillna("unknown")
df["Department"] = df["Department"].fillna("not assigned")

print(df)

     EmpID     Name    Department   Salary
901    101     Asha         Sales  45000.0
902    102  unknown            IT  60000.0
903    103    Meena            HR      NaN
904    104      sai  not assigned  89000.0

In [ ]:
df["Bonus"] = df["Salary"] * 0.10

print(df)

     EmpID     Name    Department   Salary   Bonus
901    101     Asha         Sales  45000.0  4500.0
902    102  unknown            IT  60000.0  6000.0
903    103    Meena            HR      NaN     NaN
904    104      sai  not assigned  89000.0  8900.0

In [ ]:
df.loc[df["Name"] == "sai", "Salary"] = 95000

print(df)

     EmpID     Name    Department   Salary   Bonus
901    101     Asha         Sales  45000.0  4500.0
902    102  unknown            IT  60000.0  6000.0
903    103    Meena            HR      NaN     NaN
904    104      sai  not assigned  95000.0  8900.0

In [ ]:
df.rename(columns={"EmpID": "EmployeeID"}, inplace=True)

print(df)

     EmployeeID     Name    Department   Salary   Bonus
901         101     Asha         Sales  45000.0  4500.0
902         102  unknown            IT  60000.0  6000.0
903         103    Meena            HR      NaN     NaN
904         104      sai  not assigned  95000.0  8900.0

In [ ]:
df.drop(columns=["Bonus"], inplace=True)

print(df)

     EmployeeID     Name    Department   Salary
901         101     Asha         Sales  45000.0
902         102  unknown            IT  60000.0
903         103    Meena            HR      NaN
904         104      sai  not assigned  95000.0

In [ ]:
print("Total Salary:", df["Salary"].sum())
print("Average Salary:", df["Salary"].mean())
print("Maximum Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())

Total Salary: 200000.0
Average Salary: 66666.66666666667
Maximum Salary: 95000.0
Minimum Salary: 45000.0

In [ ]:
print(df.groupby("Department")["Salary"].sum())

Department
HR                  0.0
IT              60000.0
Sales           45000.0
not assigned    95000.0
Name: Salary, dtype: float64

In [ ]:
result = df.groupby("Department").agg(
    Average_Salary=("Salary", "mean"),
    Number_of_Employees=("EmployeeID", "count")
)

print(result)

              Average_Salary  Number_of_Employees
Department
HR                       NaN                    1
IT                   60000.0                    1
Sales                45000.0                    1
not assigned         95000.0                    1

In [ ]:
import pandas as pd

df2 = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "Bonus": [4500, 6000, 5000, 9500]
})

result = pd.merge(df_emp, df2, on="EmpID")

print(result)

NameError: name 'df_emp' is not defined

In [ ]:
import pandas as pd


employees = {
    "EmpID": [101, 102, 103, 104],
    "Name": ["Asha", "unknown", "Meena", "sai"],
    "Department": ["Sales", "IT", "HR", "not assigned"],
    "Salary": [45000, 60000, None, 95000]
}

df_emp = pd.DataFrame(employees)


df2 = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "Bonus": [4500, 6000, 5000, 9500]
})


result = pd.merge(df_emp, df2, on="EmpID")

print(result)

   EmpID     Name    Department   Salary  Bonus
0    101     Asha         Sales  45000.0   4500
1    102  unknown            IT  60000.0   6000
2    103    Meena            HR      NaN   5000
3    104      sai  not assigned  95000.0   9500

In [1]:
import pandas as pd
employees = {
    "EmpID": [101, 102, 103, 104],
    "Name": ["Asha", None, "Meena", "sai"],
    "Department": ["Sales", "IT", "HR", None],
    "Salary": [45000, 60000, None, 89000]
}

I = [901, 902, 903, 904]

df = pd.DataFrame(employees, index=I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [4]:
df.groupby("Department")["Salary"].mean()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [5]:
df.groupby("Department")["Salary"].max()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [6]:
df.groupby("Department")["Salary"].std()

Department
HR      NaN
IT      NaN
Sales   NaN
Name: Salary, dtype: float64

In [7]:
df.groupby("Department")["Salary"].min()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [8]:
df.groupby("Department")["Salary"].sum()

Department
HR           0.0
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [9]:
df.groupby("Department")["Salary"].var()

Department
HR      NaN
IT      NaN
Sales   NaN
Name: Salary, dtype: float64

In [12]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

               mean      max      min
Department
HR              NaN      NaN      NaN
IT          60000.0  60000.0  60000.0
Sales       45000.0  45000.0  45000.0

In [14]:
df.groupby("Department").agg({
    "EmpID" :['mean','max'],
    "Salary" :['sum','count']
})

            EmpID        Salary
             mean  max      sum count
Department
HR          103.0  103      0.0     0
IT          102.0  102  60000.0     1
Sales       101.0  101  45000.0     1

In [17]:
import pandas as pd
data = {
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena"],
    "Age": [22, 24, 21, 25, 23, 26, 20, 27],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
             "Mumbai", "Chennai", "Bangalore", "Mumbai"],
    "Salary": [30000, 40000, 28000, 50000, 35000, 45000, 25000, 55000]
}

df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       Name  Age       City  Salary
101    Ravi   22  Hyderabad   30000
102   Priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [21]:
print(df['Name'])

101      Ravi
102     Priya
103      Arun
104     Sneha
105     Kiran
106    Anjali
107    Vikram
108     Meena
Name: Name, dtype: object

In [22]:
import pandas as pd

data = {
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena"],
    "Age": [22, 24, 21, 25, 23, 26, 20, 27],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
             "Mumbai", "Chennai", "Bangalore", "Mumbai"],
    "Salary": [30000, 40000, 28000, 50000, 35000, 45000, 25000, 55000]
}

df = pd.DataFrame(data, index=[101, 102, 103, 104, 105, 106, 107, 108])

print(df[["Name", "Salary"]])

       Name  Salary
101    Ravi   30000
102   Priya   40000
103    Arun   28000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
107  Vikram   25000
108   Meena   55000

In [23]:
print(df[df["Age"]>23])

       Name  Age       City  Salary
102   Priya   24    Chennai   40000
104   Sneha   25  Hyderabad   50000
106  Anjali   26    Chennai   45000
108   Meena   27     Mumbai   55000

In [24]:
print(df[df["Salary"]>40000])

       Name  Age       City  Salary
104   Sneha   25  Hyderabad   50000
106  Anjali   26    Chennai   45000
108   Meena   27     Mumbai   55000

In [27]:
print(df[df["City"] == "Chennai"])

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
106  Anjali   26  Chennai   45000

In [34]:
result = df[(df["Age"] > 22) & (df["Salary"] > 35000)]

print(result)

       Name  Age       City  Salary
102   Priya   24    Chennai   40000
104   Sneha   25  Hyderabad   50000
106  Anjali   26    Chennai   45000
108   Meena   27     Mumbai   55000

In [43]:
df[(df["City"] == "Mumbai") | (df["City"] == "Bangalore")]

print(df)

       Name  Age       City  Salary
101    Ravi   22  Hyderabad   30000
102   Priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [44]:
 df.loc[df["Salary"] > 30000, ["Name", "Salary"]]

print(df)

       Name  Age       City  Salary
101    Ravi   22  Hyderabad   30000
102   Priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [45]:
 df.iloc[1:4]

print(df)

       Name  Age       City  Salary
101    Ravi   22  Hyderabad   30000
102   Priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25  Hyderabad   50000
105   Kiran   23     Mumbai   35000
106  Anjali   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000